apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  workspaces:
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/surajmohan-m/webapp.git
  - name: image-reference
    value: docker.io/surajmohanm/webapp-tekton
