apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-listener
spec:
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: ci-webhook
            secretKey: secret
        - name: "eventTypes"
          value: ["push"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push')"
  
  bindings:
    - ref: github-binding
  template:
    ref: trigger-demo-template
