apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.html_url)
    - name: revision
      value: $(body.head_commit.id)
