apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-listener
spec:
  interceptors:
    - cel:
        filter: "header.match('X-GitHub-Event', 'push')"
  bindings:
    - ref: github-binding
  template:
    ref: trigger-demo-template
