apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webapp-listener
spec:
  resources:
    kubernetesResource:
      serviceType: NodePort
  serviceAccountName: tekton-robot
  triggers:
    - name: hello-trigger 
      bindings:
      - ref: github-binding
      template:
        ref: trigger-demo-template
