apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-demo-template
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: repo-url
      description: The git repository that hosts context
    - name: revision
      description: The git repository that hosts context  
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: clone-build-push-run-
        annotations:
          tekton.dev/gitURL: "$(tt.params.repo-url)"
      spec:
        pipelineRef:
          name: clone-build-push
        workspaces:
        - name: docker-credentials
          secret:
            secretName: docker-credentials
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        params:
        - name: repo-url
          value: "$(tt.params.repo-url)"
        - name: image-reference
          value: surajmohanm/webapp-tekton
