apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: tekton-pipelinerun-
spec:
  serviceAccountName: dockerhub-service-account
  pipelineRef:
    name: tekton-pipeline 
  params:
  - name: repo-url
    value: https://github.com/surajmohan-m/webapp
  - name: image-reference
    value: docker.io/surajmohanm/webapp-tekton
  - name: image-tag
    value: latest
  workspaces:
    - name: tekton-workspace 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
